Validate events
retracedhq/retraced pull request #821
Opened 2023-04-10 11:01 UTC by ukrocks007

Thank you for contributing to Retraced!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #793

2023-04-10 11:52 UTC, deepakprabhakara commented on package.json
> +    "joi": "^17.9.1",
pin the version

2023-04-11 14:44 UTC, ukrocks007 commented
@deepakprabhakara are we allowing teamId in the event schema?

2023-04-12 23:14 UTC, deepakprabhakara approved these changes

2023-04-12 23:14 UTC, deepakprabhakara commented
> @deepakprabhakara are we allowing teamId in the event schema?

No.

2023-04-12 23:17 UTC, deepakprabhakara requested changes
crud is optional

2023-04-12 23:17 UTC, deepakprabhakara commented on src/handlers/createEvent.ts
> +  crud: Joi.string().valid("c", "r", "u", "d").required(),
crud is optional

2023-04-13 11:24 UTC, deepakprabhakara approved these changes

2023-04-13 11:24 UTC, merged